feat: add entity IRD
Midna3/api-gestor pull request #10
Opened 2022-05-06 17:19 UTC by LuizMFL

Pode existir discordância no comentário do getPercentageMediaTotal pois não entendi direito a proposta do IRDMediaTotal do Banco de dados:
```/**
     * Retorna a porcentagem de professores que se encaixam na Media Total.
     *
     * @return double representando essa porcentagem.
     */
    public double getPercentageMediaTotal() {
        return percentageMediaTotal;
    }
```

2022-05-06 22:14 UTC, moesio-f commented on src/main/java/edu/apigestor/entity/domain/IRD.java
> +    private double percentageAlta;
Por enquanto, não vamos nem precisar acessar esses dados. Só estamos preocupados com a média, então podemos remover para deixar a classe mais simples e evitar gold plating.

2022-05-06 22:20 UTC, moesio-f commented on src/main/java/edu/apigestor/entity/domain/IRD.java
> +    }
Nesse caso, não é indicada a porcentagem, e sim a média do IRD (Índice de Regularidade Docente) que os docentes se encaixam.  Esse índice varia de 0 a 5, assim a média também está dentro desse intervalo. Talvez seja uma boa mudar o nome do atributo e do método get.

Mais informações sobre esse índice podem ser encontradas aqui: https://ajuda.focoescola.com.br/hc/pt-br/articles/360052480393

2022-05-06 22:21 UTC, moesio-f requested changes
Massa, acredito que possam ser realizadas duas mudanças:

1. Remoção das colunas que não vamos utilizar no momento (simplificamos a estrutura da classe).
2. Alterar o nome do atributo da média para algo mais significativo.

2022-05-07 00:28 UTC, Arthursca requested changes
Remover os atributos não referentes a MediaTotal

2022-05-07 00:43 UTC, moesio-f approved these changes

2022-05-07 00:44 UTC, Arthursca approved these changes

2022-05-07 00:44 UTC, merged