feat: add entity IED
Midna3/api-gestor pull request #7
Opened 2022-05-04 13:00 UTC by LuizMFL

Entidade baseada no ultimo Commit da entidade AFD criada por Moesio.

2022-05-06 03:32 UTC, moesio-f approved these changes
Acredito que tudo certo por aqui, não encontrei nenhuma incosistência.

2022-05-06 11:11 UTC, moesio-f requested changes
Um detalhe que percebi enquanto revisava os PRs #8 e #1: precisamos de uma coluna para o ano. Pro caso do IED, essa coluna também entra na chave já que é chave primária.

2022-05-06 18:47 UTC, LuizMFL commented
Adicionado a PK ano ao IED

2022-05-06 21:21 UTC, moesio-f approved these changes

2022-05-07 00:50 UTC, Arthursca approved these changes

2022-05-07 00:50 UTC, merged