feat: add entity ICG
Midna3/api-gestor pull request #8
Opened 2022-05-06 01:16 UTC by mrjohnnus

Entidade ICG criada com base na entidade AFD criada por Moésio.

2022-05-06 03:15 UTC, moesio-f commented on src/main/java/edu/apigestor/entity/domain/ICG.java
> +}
Lembrar de adicionar uma quebra de linha ao final do arquivo.

2022-05-06 03:16 UTC, moesio-f commented on src/main/java/edu/apigestor/entity/domain/ICG.java
> +    public static class AFDKey implements Serializable {
Nome da classe interna não bate com o utilizado em `@IdClass(ICG.ICGKey.class)` (linha 22)

2022-05-06 03:27 UTC, moesio-f requested changes
Massa! Boa implementação inicial, só tem algumas coisas que precisam ser revisadas. Vou indicar os detalhes que percebi: 

1. Existem alguns erros de sintaxe e alguns nomes utilizados na classe original (AFD). Por exemplo, a classe interna ainda está com o nome `AFDKey` (amanhã mostro as modificações para conseguir importar os módulos do JPA, aí vai ficar mais fácil identificar os erros).
2. Para essa entidade em específico, não temos nenhum requisito que necessita das porcentagens de cada classe, apenas precisamos do ICG médio (coluna `ICGNivelMedio`, já que quando temos essa informação relativa a uma escola específica essa é a única coluna que vai possuir um valo). Vale dar uma olhada no épico H013 e na história H006 que tratam sobre esse indicador. 
3. Sempre lembrar de usar a formatação do Google para Java (aí conseguimos manter uma padronização entre os códigos), vou mostrar isso com calma amanhã 😃

2022-05-06 03:51 UTC, moesio-f commented on src/main/java/edu/apigestor/entity/domain/ICG.java
> +}
Outro detalhe, lembrar de inserir uma quebra de linha no final do arquivo.

2022-05-06 05:12 UTC, mrjohnnus commented on src/main/java/edu/apigestor/entity/domain/ICG.java
> +}
> 2. Para essa entidade em específico, não temos nenhum requisito que necessita das porcentagens de cada classe, apenas precisamos do ICG médio (coluna ICGNivelMedio, já que quando temos essa informação relativa a uma escola específica essa é a única coluna que vai possuir um valo). Vale dar uma olhada no épico H013 e na história H006 que tratam sobre esse indicador.

Sobre o ICGNivelMedio, eu tava checando no banco e a coluna tá vazia, puxei 5000 rows e nada. Ficou faltando mesmo ou é só tirar a média com os níveis que tem?

2022-05-06 05:12 UTC, mrjohnnus commented on src/main/java/edu/apigestor/entity/domain/ICG.java
> +}
> 2. Para essa entidade em específico, não temos nenhum requisito que necessita das porcentagens de cada classe, apenas precisamos do ICG médio (coluna ICGNivelMedio, já que quando temos essa informação relativa a uma escola específica essa é a única coluna que vai possuir um valo). Vale dar uma olhada no épico H013 e na história H006 que tratam sobre esse indicador.

Sobre o ICGNivelMedio, eu tava checando no banco e a coluna tá vazia, puxei 5000 rows e nada. Ficou faltando mesmo ou é só tirar a média com os níveis que tem?

2022-05-06 05:14 UTC, mrjohnnus commented
Deixei a identação no padrão do Google (por mais que me doa), corrigi os restos que ficaram da classe original (AFD) e creio que erros de sintaxe. Qualquer coisa a gente discute mais fundo na reunião.

2022-05-06 11:03 UTC, moesio-f commented on src/main/java/edu/apigestor/entity/domain/ICG.java
> +}
Tem algumas vazias mesmo, se filtrar pelas não nulas tu vai encontrar bastante (~998907 linhas).

```sql
SELECT count(*) FROM educacao.icg WHERE ICGNivelMedio is not null;
```

2022-05-06 11:09 UTC, moesio-f requested changes
Fica só faltando um detalhe (que acabei esquecendo de colocar no `AFD` também): precisamos de uma coluna com o ano (também precisa ser colocada dentro da chave, já que o ano é chave primária na tabela `icg`).

2022-05-06 12:41 UTC, JPedroFreire commented on src/main/java/edu/apigestor/entity/domain/ICG.java
> +}
Eu até pensei em fazer isso, mas só pegar as primeiras 5000 linhas me pareceu um esforço suficiente na hora, mas que infelizmente se mostrou errado KKKKKK. Tranquilo esse ponto então.

2022-05-06 13:25 UTC, moesio-f commented on src/main/java/edu/apigestor/entity/domain/ICG.java
> +}
Sim kkkkkkkkk a msm coisa aqui, tinha umas tabelas que as primeiras linhas eram todas null

2022-05-07 00:44 UTC, Arthursca requested changes

2022-05-07 00:44 UTC, Arthursca commented on src/main/java/edu/apigestor/entity/domain/ICG.java
> +
Está faltando o atributo "Ano"

2022-05-09 16:02 UTC, moesio-f approved these changes
Aceitando esse PR, qualquer problema corrigimos depois.

2022-05-09 16:03 UTC, merged